#-------------------------------
# General Site Settings
title: 'Lib: W'
#logo: logo.svg # You can add own logo.
description: A personal homepage and blog of Wenhui Wu



#-------------------------------

# Author Settings
author:
  name: Wenhui Wu
  image: 01.jpeg
  say-hello: Hello, I’m Wu.
  bio: Welcome to my blog! I am a traffic engineering student. And I am interested in <b>computer science</b>, <b>music</b>, <b>photography</b>, <b>traveling</b> and <b>video games</b> as well! </br></br>Contact <a href="mailto:hi_wu@outlook.com">Hi_Wu@outlook.com</a> 

  #Social media links are remained undone

#-------------------------------

# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false# To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------

# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

